version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/manage-products
      - JWT_SECRET=YWUHN&SHNAZHAKAA
      - JWT_EXPIRES_IN=7d
      - LOG_LEVEL=debug
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
