version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/manage-products
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=YWUHN&SHNAZHAKAA
      - JWT_EXPIRES_IN=7d
      - LOG_LEVEL=debug
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data:
